# Stacking Ensemble

In [2]:
from mlxtend.classifier import (StackingClassifier, LogisticRegression)

In [1]:
## Importing Libraries

from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [ ]:
##Creating a loop so that data the output of these models combined together used as the input for the meta model.

In [4]:
clfs = [
x()
for x in [
LogisticRegression,
DecisionTreeClassifier,
KNeighborsClassifier,
GaussianNB,
SVC,
RandomForestClassifier,
]
]

In [5]:
from dataclasses import dataclass
import pandas as pd
import numpy as np


# Import train_test_split from sklearn library
from sklearn.model_selection import train_test_split

# Read the dataset from csv fiel using pandas library
dataset = pd.read_excel(r"C:\Users\karun\Documents\TrendingVirus\Final_Project_dataset_V2.xlsx")
dataset



Case no. Date of notification to WHO (yyyy/mm/dd) Reporting country  \
0            1                               2017-08-15      Saudi Arabia   
1            2                               2017-08-16      Saudi Arabia   
2            3                               2017-08-18      Saudi Arabia   
3            4                               2017-08-21      Saudi Arabia   
4            5                               2017-08-24      Saudi Arabia   
...        ...                                      ...               ...   
2434         5                               2017-01-04      Saudi Arabia   
2435         6                               2017-01-04      Saudi Arabia   
2436         7                               2017-01-04      Saudi Arabia   
2437         8                               2017-01-02      Saudi Arabia   
2438         9                               2017-01-02      Saudi Arabia   

     City of residence  Age Sex Health care worker Comorbidities  \
0             Madinah    67   M                 No           Yes   
1               Jeddah   69   M                 No           Yes   
2               Jeddah   51   M                 No           Yes   
3               Riyadh   48   M                 No           Yes   
4      Dawmet Aljandal   40   F                 No           Yes   
...                ...  ...  ..                ...           ...   
2434           Buridah   87   F                 No           Yes   
2435            Riyadh   56   M                 No           Yes   
2436            Riyadh   59   M                 No            NR   
2437           Madinah   70   M                 No           Yes   
2438           Buridah   63   F                 No           Yes   

     Exposure to camels Camel milk consumption Exposure to MERS-CoV cases  \
0                   Yes                     No                         No   
1                    No                     No                         No   
2                    No                     No                         No   
3                   Yes                    Yes                         No   
4                    No                     No                         No   
...                 ...                    ...                        ...   
2434                 No                     No                         No   
2435                 No                     No                         No   
2436                 No                     No                        Yes   
2437                Yes                    Yes                         No   
2438                 No                     No                         No   

     Date of symptoms onset (yyyy/mm/dd)  \
0                    2017-08-12 00:00:00   
1                    2017-08-13 00:00:00   
2                    2017-08-11 00:00:00   
3                    2017-08-18 00:00:00   
4                    2017-08-17 00:00:00   
...                                  ...   
2434                 2016-12-29 00:00:00   
2435                 2016-12-28 00:00:00   
2436                                 NaN   
2437                 2016-12-25 00:00:00   
2438                 2016-12-29 00:00:00   

     Date of first hospitalization (yyyy/mm/dd)  \
0                           2017-08-14 00:00:00   
1                           2017-08-15 00:00:00   
2                           2017-08-17 00:00:00   
3                           2017-08-20 00:00:00   
4                           2017-08-21 00:00:00   
...                                         ...   
2434                        2017-01-02 00:00:00   
2435                        2017-01-02 00:00:00   
2436                                        NaN   
2437                        2017-01-01 00:00:00   
2438                        2016-12-31 00:00:00   

     Date of laboratory confirmation (yyyy/mm/dd)  Day_diff    Status  
0                                      2017-08-14       2.0     Alive  
1                                      2017-08-15    

In [5]:
#dataset =pd.get_dummies(dataset, columns = ['Reporting country','City of residence','Sex','Health care worker','Comorbidities','Exposure to camels','Camel milk consumption','Exposure to MERS-CoV cases'])

In [ ]:
#dataset =pd.get_dummies(dataset, columns = ['Reporting country','City of residence','Sex','Health care worker','Comorbidities','Exposure to camels','Camel milk consumption','Exposure to MERS-CoV cases'])

In [6]:
##Droping the date columns from the data set

New_dataset = dataset.drop(['Date of notification to WHO (yyyy/mm/dd)', 'Date of symptoms onset (yyyy/mm/dd)', "Date of first hospitalization (yyyy/mm/dd)",'Date of laboratory confirmation (yyyy/mm/dd)'], axis=1)

In [24]:
New_dataset

Case no. Reporting country City of residence  Age Sex  \
0            1      Saudi Arabia          Madinah    67   M   
1            2      Saudi Arabia            Jeddah   69   M   
2            3      Saudi Arabia            Jeddah   51   M   
3            4      Saudi Arabia            Riyadh   48   M   
4            5      Saudi Arabia   Dawmet Aljandal   40   F   
...        ...               ...               ...  ...  ..   
2434         5      Saudi Arabia           Buridah   87   F   
2435         6      Saudi Arabia            Riyadh   56   M   
2436         7      Saudi Arabia            Riyadh   59   M   
2437         8      Saudi Arabia           Madinah   70   M   
2438         9      Saudi Arabia           Buridah   63   F   

     Health care worker Comorbidities Exposure to camels  \
0                    No           Yes                Yes   
1                    No           Yes                 No   
2                    No           Yes                 No   
3                    No           Yes                Yes   
4                    No           Yes                 No   
...                 ...           ...                ...   
2434                 No           Yes                 No   
2435                 No           Yes                 No   
2436                 No            NR                 No   
2437                 No           Yes                Yes   
2438                 No           Yes                 No   

     Camel milk consumption Exposure to MERS-CoV cases  Day_diff    Status  
0                        No                         No       2.0     Alive  
1                        No                         No       2.0     Alive  
2                        No                         No       6.0     Alive  
3                       Yes                         No       2.0     Alive  
4                        No                         No       5.0     Alive  
...                     ...                        ...       ...       ...  
2434                     No                         No       6.0     Alive  
2435                     No                         No       7.0     Alive  
2436                     No                        Yes       NaN     Alive  
2437                    Yes                         No       8.0     Alive  
2438                     No                         No       3.0  Deceased  

[2439 rows x 12 columns]

In [7]:
##Converting the dataset into string

New_dataset = New_dataset.applymap(str)
New_dataset.dtypes

Case no.                      object
Reporting country             object
City of residence             object
Age                           object
Sex                           object
Health care worker            object
Comorbidities                 object
Exposure to camels            object
Camel milk consumption        object
Exposure to MERS-CoV cases    object
Day_diff                      object
Status                        object
dtype: object

In [8]:
##Creating a replica of the dataset 
Dataset3 = New_dataset.copy()

In [11]:
#Convert categorical variables to numeric using LabelEncoder

New_dataset = np.array(New_dataset)

for i in range(New_dataset.shape[1]):
    lbl = preprocessing.LabelEncoder()
    lbl.fit(list(New_dataset[:,i]))
    New_dataset[:, i] = lbl.transform(New_dataset[:, i])

In [12]:
## converting the data into integer type

New_dataset = New_dataset.astype(int)

In [13]:
New_dataset

array([[ 0,  3, 42, ...,  0,  8,  0],
       [14,  3, 37, ...,  0,  8,  0],
       [34,  3, 37, ...,  0, 13,  0],
       ...,
       [44,  3, 49, ...,  1, 17,  0],
       [45,  3, 41, ...,  0, 15,  0],
       [46,  3, 24, ...,  0, 10,  2]])

In [15]:
New_dataset.shape

(2439, 12)

In [14]:
# Converting Dead or Alive to numbers 

#from sklearn.preprocessing import LabelEncoder

#lb_make = LabelEncoder()
#New_dataset["make_code"] = lb_make.fit_transform(New_dataset["Status"])
#New_dataset[["Status", "make_code"]]

In [23]:
#Standardising the Dataset

new_df = pd.DataFrame(StandardScaler().fit_transform(New_dataset))
new_df

0         1         2         3         4         5         6  \
0    -1.264701 -0.199092  0.215044  0.929839  0.639541 -0.499487  0.791253   
1    -0.479443 -0.199092 -0.118391  1.045024  0.639541 -0.499487  0.791253   
2     0.642354 -0.199092 -0.118391  0.008359  0.639541 -0.499487  0.791253   
3     1.034983 -0.199092  0.681853 -0.164418  0.639541 -0.499487  0.791253   
4     1.091073 -0.199092 -0.785260 -0.625158 -1.563622 -0.499487  0.791253   
...        ...       ...       ...       ...       ...       ...       ...   
2434  1.091073 -0.199092 -0.985321  1.966503 -1.563622 -0.499487  0.791253   
2435  1.147163 -0.199092  0.681853  0.296321  0.639541 -0.499487  0.791253   
2436  1.203253 -0.199092  0.681853  0.469099  0.639541 -0.499487 -1.892845   
2437  1.259343 -0.199092  0.148357  1.102616  0.639541 -0.499487  0.791253   
2438  1.315433 -0.199092 -0.985321  0.699469 -1.563622 -0.499487  0.791253   

             7         8         9        10        11  
0     1.614927 -0.542758 -0.828687 -0.867768 -0.611947  
1    -0.619223 -0.542758 -0.828687 -0.867768 -0.611947  
2    -0.619223 -0.542758 -0.828687  0.164362 -0.611947  
3     1.614927  1.842443 -0.828687 -0.867768 -0.611947  
4    -0.619223 -0.542758 -0.828687 -0.042064 -0.611947  
...        ...       ...       ...       ...       ...  
2434 -0.619223 -0.542758 -0.828687  0.164362 -0.611947  
2435 -0.619223 -0.542758 -0.828687  0.370788 -0.611947  
2436 -0.619223 -0.542758  1.206728  0.990067 -0.611947  
2437  1.614927  1.842443 -0.828687  0.577215 -0.611947  
2438 -0.619223 -0.542758 -0.828687 -0.454916  1.642643  

[2439 rows x 12 columns]

In [30]:
#New_dataset.to_csv(r"C:\Users\karun\Documents\TrendingVirus\test.csv")

#dataset_2 = pd.read_csv(r"C:\Users\karun\Documents\TrendingVirus\test.csv")

In [46]:

X = new_df.iloc[1:, :10].values # Here first : means fetch all rows :-1 means except last column
y = new_df.iloc[1:, 11].values # : is fetch all rows 16 means 16 column
y


array([-0.61194691, -0.61194691, -0.61194691, ..., -0.61194691,
       -0.61194691,  1.64264299])

In [49]:
##Converting the Final predictor as integer
y = y.astype(int)
y

array([0, 0, 0, ..., 0, 0, 1])

In [55]:
# random_state below is a metric that is used by the function to shuffle datas while splitting. If you change the random_state
# then your split may not be same as previous
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state = 2) # 0.2 test_size means 20%

In [39]:
#@dataclass
#class StackingClassifierParams:
    ##y_train: np.ndarray
    #X_val: pd.DataFrame
    #y_val: np.ndarray

In [40]:
#dataset = StackingClassifierParams(X_train,y_train, X_val, y_val)

In [51]:
stack = StackingClassifier(classifiers=clfs,meta_classifier=LogisticRegression(),)

In [52]:
y_train.shape


(1950,)

In [28]:
X_train.shape

(1950, 10)

In [65]:
from sklearn import model_selection

In [67]:
stack.fit(X_train, y_train)


StackingClassifier(average_probas=False,
                   classifiers=[<mlxtend.classifier.logistic_regression.LogisticRegression object at 0x0000020BB189D308>,
                                DecisionTreeClassifier(ccp_alpha=0.0,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features=None,
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split...
                                                       min_weight_fraction_leaf=0.0,
 

In [58]:
model_score = stack.score(X_val,y_val)

In [59]:
model_score

0.9836065573770492

In [70]:
print(
f"{stack.__class__.__name__} "
f"AUC# {model_score: .3f}"
)

StackingClassifier AUC#  0.984
